nome = input('Digite o seu nome completo: ').strip()
print(nome.upper())
print(nome.lower())
print('O seu nome tem no total: {} letras'.format(len(nome) - nome.count(' ')))
#print('O seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('O seu primeiro nome é {} e tem {} letras.'.format(separa[0], len(separa[0])))
